device_info:
  device:
    name: staubli_robot
  manufacturer:
    name: Staubli
    uuid: ee260e78-d731-415a-84ca-4b02c487410c
  model:
    name: Staubli_TX60
    uuid: 9ad3c0ee-ec5e-4057-a297-d340e1484f01
  user_description: Rethink Robotics Sawyer Robot
  serial_number: 123456789
  device_classes:
    - class_identifier:
        name: robot
        uuid: 39b513e7-21b9-4b49-8654-7537473030eb
      subclasses: 
        - serial
        - serial_six_axis        
  implemented_types:
    - com.robotraconteur.robotics.robot.Robot
robot_type: serial
robot_capabilities:
- jog_command
- trajectory_command
- position_command
chains:
- kin_chain_identifier: robot_arm
  H:
  - x: 0.0
    y: 0.0
    z: 1.0
  - x: 0.0
    y: 1.0
    z: 0.0
  - x: 0.0
    y: 1.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 1.0
  - x: 0.0
    y: 1.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 1.0
  P:
  - x: 0.0
    y: 0.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 0.375
  - x: 0.0
    y: 0.02
    z: 0.29
  - x: 0.0
    y: 0.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 0.31
  - x: 0.0
    y: 0.0
    z: 0.07
  - x: 0.0
    y: 0.0
    z: 0.0
  flange_identifier: tool0
  flange_pose:
    orientation:
      w: 0.7071067811882787
      x: 0.0
      y: 0.7071067811848163
      z: 0.0
    position:
      x: 0.0
      y: 0.0
      z: 0.0
  joint_numbers:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5  
joint_info:
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_1
  joint_limits:
    effort: 1000.0
    lower: -3.14159265
    upper: 3.14159265
    velocity: 5.027
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_2
  joint_limits:
    effort: 1000.0
    lower: -2.2252948
    upper: 2.2252948
    velocity: 4.189
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_3
  joint_limits:
    effort: 1000.0
    lower: -2.48709418
    upper: 2.48709418
    velocity: 5.236
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_4
  joint_limits:
    effort: 1000.0
    lower: -4.71238898
    upper: 4.71238898
    velocity: 6.981
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_5
  joint_limits:
    effort: 1000.0
    lower: -2.13802833
    upper: 2.31256126
    velocity: 7.069
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_6
  joint_limits:
    effort: 1000.0
    lower: -4.71238898
    upper: 4.71238898
    velocity: 10.472
  joint_type: revolute
  passive: false
